name: Deploy to STG

on:
  release:
    types:
      - prereleased

jobs:
  deploy:
    uses: ./.github/workflows/deploy-api-documentation.yml
    with:
      environment: stg
    permissions:
      actions: read
      contents: read
      repository-projects: read
      pull-requests: read
      pages: write
      id-token: write
