name: Deploy to DEV

on:
  push:
    branches:
      - dev-test

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  deploy:
    uses: ./.github/workflows/deploy-api-documentation.yml
    with:
      environment: dev
