name: Deploy to DEV

on:
  push:
    branches:
      - dev-test

jobs:
  deploy:
    uses: ./.github/workflows/deploy-api-documentation.yml
    with:
      environment: dev
    permissions:
      actions: read
      contents: read
      repository-projects: read
      pull-requests: read
      pages: write
      id-token: write
